[general]
import = [
    "~/.config/alacritty/themes/themes/ashes_dark.toml"
]

[window]
dimensions = { columns = 105, lines = 27 }
position = { x = 750, y = 600 }
padding = { x = 20, y = 36 }
dynamic_padding = true
decorations = "Transparent"
opacity = 0.87
blur = true


[scrolling]
history = 100000
multiplier = 5

[font]
size = 17.0
offset = { x = 0, y = 4 }
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }
